openapi: "3.0.0"

info:
  title: Hello World
  version: "1.0"
servers:
  - url: /openapi

paths:
  /streaming:
    post:
      summary: Generate stream
      description: Generates a stream.
      operationId: run.streaming
      responses:
        "200":
          description: streaming response
          content:
            text/plain:
              schema:
                type: string
                example: "Hello, world!"
